import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { apiClient } from "@/lib/api-client";

export const downloadSAR = async (reportId: string): Promise<boolean> => {
  try {
    const res = await apiClient.get(`/api/v1/sars/${reportId}/export`);
    if (!res.data || !res.data.sar_report) return false;

    const sar = res.data.sar_report;
    const meta = sar.report_metadata;
    const sub = sar.subject_information;
    const act = sar.suspicious_activity;

    const doc = new jsPDF("p", "pt", "a4");

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(220, 53, 69);
    doc.text("CONFIDENTIAL: SUSPICIOUS ACTIVITY REPORT", 40, 40);

    doc.setTextColor(0, 0, 0);

    // Section 1: Metadata
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("Report Information", 40, 70);
    doc.setFont("helvetica", "normal");
    doc.text(`Report ID: ${meta.report_id}`, 40, 90);
    doc.text(`Generated: ${new Date(meta.generated_timestamp).toLocaleString()}`, 40, 105);
    doc.text(`Type: ${meta.report_type} | Risk Level: ${meta.risk_level}`, 40, 120);

    doc.setFont("helvetica", "bold");
    doc.text("Reporting Institution", 300, 70);
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${meta.reporting_institution.institution_name}`, 300, 90);
    doc.text(`Code: ${meta.reporting_institution.branch_code} | ${meta.reporting_institution.country}`, 300, 105);

    // Section 2: Subject Info
    doc.setFont("helvetica", "bold");
    doc.text("Subject Information", 40, 150);
    autoTable(doc, {
      startY: 160,
      head: [['Customer ID', 'Name', 'DOB', 'KYC Status']],
      body: [[sub.customer_id, sub.name, sub.date_of_birth, sub.kyc_status]],
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] }
    });

    // Account Details
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Account ID', 'Type', 'Opened', 'Status']],
      body: [[sub.account_details.account_id, sub.account_details.account_type, sub.account_details.account_opened_date, sub.account_details.account_status]],
      theme: 'grid',
      headStyles: { fillColor: [52, 73, 94] }
    });

    // Section 3: Suspicious Activity
    let nextY = (doc as any).lastAutoTable.finalY + 30;
    doc.setFont("helvetica", "bold");
    doc.text("Activity Details", 40, nextY);
    autoTable(doc, {
      startY: nextY + 10,
      head: [['Activity Type', 'Flagged Txns', 'Total Amount', 'First Detected', 'Last Detected']],
      body: [[
        act.activity_type, 
        act.total_transactions_flagged, 
        `${act.amount || act.total_amount} ${act.currency || ''}`, 
        new Date(act.first_detected).toLocaleDateString(), 
        new Date(act.last_detected).toLocaleDateString()
      ]],
      theme: 'grid',
      headStyles: { fillColor: [192, 57, 43] }
    });

    // Section 4: Narrative
    nextY = (doc as any).lastAutoTable.finalY + 30;
    doc.setFont("helvetica", "bold");
    doc.text("Narrative & Analysis", 40, nextY);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    
    // Auto-wrap text lines (max width ~510pt for A4)
    const lines1 = doc.splitTextToSize(`Summary: ${sar.narrative.summary}`, 510);
    doc.text(lines1, 40, nextY + 15);
    
    let yy = nextY + 15 + (lines1.length * 12);
    const lines2 = doc.splitTextToSize(`Analysis: ${sar.narrative.analysis}`, 510);
    doc.text(lines2, 40, yy);
    
    yy += (lines2.length * 12);
    const lines3 = doc.splitTextToSize(`Recommendation: ${sar.narrative.recommendation}`, 510);
    doc.text(lines3, 40, yy);

    // Section 5: Transactions Table
    yy += (lines3.length * 12) + 20;
    if (yy > 700) {
      doc.addPage();
      yy = 40;
    }
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("Flagged Transactions", 40, yy);

    const txnBody = (sar.transactions || []).map((t: any) => [
      t.txn_id,
      new Date(t.timestamp).toLocaleString(),
      `${t.amount} ${t.currency}`,
      t.channel,
      t.sender_account,
      t.receiver_account,
      t.risk_score
    ]);

    autoTable(doc, {
      startY: yy + 10,
      head: [['Txn ID', 'Time', 'Amount', 'Channel', 'Sender', 'Receiver', 'Risk']],
      body: txnBody,
      theme: 'grid',
      headStyles: { fillColor: [142, 68, 173] },
      styles: { fontSize: 8 }
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount} - Automatically generated by AML Pipeline`, 40, 800);
        if (sar.evidence && sar.evidence.model_version) {
          doc.text(`Model Version: ${sar.evidence.model_version}`, 400, 800);
        }
    }

    doc.save(`${meta.report_id}_SAR.pdf`);
    return true;
  } catch (error) {
    console.error("Failed downloading SAR document", error);
    return false;
  }
};
